variables:
  CONTAINER_VERSIONED_IMAGE_STAGING: $CI_REGISTRY_IMAGE/staging:$CI_PIPELINE_ID
  CONTAINER_RELEASE_IMAGE_STAGING: $CI_REGISTRY_IMAGE/staging:latest
  CONTAINER_VERSIONED_IMAGE_PRODUCTION: $CI_REGISTRY_IMAGE/production:$CI_PIPELINE_ID
  CONTAINER_RELEASE_IMAGE_PRODUCTION: $CI_REGISTRY_IMAGE/production:latest

staging_build:
  environment:
    name: staging
  stage: build
  image: docker/compose:1.27.0
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose --project-name screenapp -f docker-compose.yml -f docker-compose.staging.yml build
    - docker tag screenapp_server $CONTAINER_VERSIONED_IMAGE_STAGING
    - docker tag screenapp_server $CONTAINER_RELEASE_IMAGE_STAGING
    - docker push $CONTAINER_VERSIONED_IMAGE_STAGING
    - docker push $CONTAINER_RELEASE_IMAGE_STAGING
  only:
    - none

staging_deploy:
  environment:
    name: staging
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
  only:
    - none

production_build:
  environment:
    name: production
  stage: build
  image: docker/compose:1.27.0
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose --project-name screenapp -f docker-compose.yml -f docker-compose.production.yml build
    - docker tag screenapp_server $CONTAINER_VERSIONED_IMAGE_PRODUCTION
    - docker tag screenapp_server $CONTAINER_RELEASE_IMAGE_PRODUCTION
    - docker push $CONTAINER_VERSIONED_IMAGE_PRODUCTION
    - docker push $CONTAINER_RELEASE_IMAGE_PRODUCTION
  only:
    - tags

production_deploy:
  environment:
    name: production
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
  only:
    - tags
