variables: 
  REGISTRY_ACCESS_KEY: $REGISTRY_ACCESS_KEY
  REGISTRY_ACCESS_USER: $REGISTRY_ACCESS_USER

staging_build:
  stage: build
  image: meetrix/docker-compose-sshd
  environment:
    name: staging
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      {
        echo "@meetrix:registry=https://gitlab.com/api/v4/packages/npm/"  
        echo "//gitlab.com/api/v4/packages/npm/:_authToken=$REGISTRY_ACCESS_KEY"
      } >> .npmrc
    - export DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE build
  only:
    - master

staging_deploy:
  stage: deploy
  image: meetrix/docker-compose-sshd
  environment:
    name: staging
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      {
        echo "@meetrix:registry=https://gitlab.com/api/v4/packages/npm/"  
        echo "//gitlab.com/api/v4/packages/npm/:_authToken=$REGISTRY_ACCESS_KEY"
      } >> .npmrc
    - export DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST
    - ssh $SSH_USER@$SSH_HOST "sudo mkdir -p /var/log/webrtc-backend && sudo chmod 777 -R /var/log/webrtc-backend"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-server' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d server
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-server >> /var/log/webrtc-backend/server.log 2>&1 &"
  only:
    - master

production_build:
  stage: build
  image: docker/compose:debian-1.29.2
  environment:
    name: production
  before_script:
    - apt update && apt -y install ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      {
        echo "@meetrix:registry=https://gitlab.com/api/v4/packages/npm/"  
        echo "//gitlab.com/api/v4/packages/npm/:_authToken=$REGISTRY_ACCESS_KEY"
      } >> .npmrc
    - export DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST
    - docker-compose -f docker-compose.yml -f docker-compose.production.yml --env-file $ENVFILE build
  only:
    - tags

production_deploy:
  stage: deploy
  image: docker/compose:debian-1.29.2
  environment:
    name: production
  before_script:
    - apt update && apt -y install ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      {
        echo "@meetrix:registry=https://gitlab.com/api/v4/packages/npm/"  
        echo "//gitlab.com/api/v4/packages/npm/:_authToken=$REGISTRY_ACCESS_KEY"
      } >> .npmrc
    - export DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST
    - ssh $SSH_USER@$SSH_HOST "sudo mkdir -p /var/log/webrtc-backend && sudo chmod 777 -R /var/log/webrtc-backend"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-server' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.production.yml --env-file $ENVFILE up -d server
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-server >> /var/log/webrtc-backend/server.log 2>&1 &"
  only:
    - tags
