staging_build:
  stage: build
  image: meetrix/docker-compose-sshd
  environment:
    name: staging
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - export DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE build
  only:
    - master

staging_deploy:
  stage: deploy
  image: meetrix/docker-compose-sshd
  environment:
    name: staging
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - export DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST
    - ssh $SSH_USER@$SSH_HOST "sudo mkdir -p /var/log/webrtc-backend && sudo chmod 777 -R /var/log/webrtc-backend"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-mongodb' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d mongo
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-mongodb >> /var/log/webrtc-backend/mongo.log 2>&1 &"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-mongo-express' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d mongo-express
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-mongo-express >> /var/log/webrtc-backend/mongo-express.log 2>&1 &"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-server' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d server
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-server >> /var/log/webrtc-backend/server.log 2>&1 &"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-redis' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d redis
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-redis >> /var/log/webrtc-backend/redis.log 2>&1 &"
  only:
    - master

production_build:
  stage: build
  image: meetrix/docker-compose-sshd
  environment:
    name: production
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - export DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST
    - docker-compose -f docker-compose.yml -f docker-compose.production.yml --env-file $ENVFILE build
  only:
    - tags

production_deploy:
  stage: deploy
  image: meetrix/docker-compose-sshd
  environment:
    name: production
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - export DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST
    - ssh $SSH_USER@$SSH_HOST "sudo mkdir -p /var/log/webrtc-backend && sudo chmod 777 -R /var/log/webrtc-backend"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-mongodb' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d mongo
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-mongodb >> /var/log/webrtc-backend/mongo.log 2>&1 &"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-mongo-express' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d mongo-express
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-mongo-express >> /var/log/webrtc-backend/mongo-express.log 2>&1 &"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-server' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d server
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-server >> /var/log/webrtc-backend/server.log 2>&1 &"
    - ssh $SSH_USER@$SSH_HOST "kill -9 \$(ps aux | grep 'logs -f webrtc-backend-redis' | grep 'docker' | awk '{print \$2}') &"
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml --env-file $ENVFILE up -d redis
    - ssh $SSH_USER@$SSH_HOST "docker logs -f webrtc-backend-redis >> /var/log/webrtc-backend/redis.log 2>&1 &"
  only:
    - tags
