version: '3.8'
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: webrtc-backend-server
    ports:
      - 9111:9100
    environment:
      VIRTUAL_HOST: ${BACKEND_DOMAIN}
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - mongo
      - redis
    command: [ 'npm', 'start' ]