version: '3.8'
services:
  redis:
    restart: always
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: webrtc-backend-server
    ports:
      - 9111:9100
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      VIRTUAL_HOST: ${BACKEND_DOMAIN}
      SESSION_SECRET: ${SESSION_SECRET}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      CORS_REGEX: ${CORS_REGEX}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      RECEIVER_EMAIL: ${RECEIVER_EMAIL}
      SENDER_EMAIL: ${SENDER_EMAIL}
      AUTH_LANDING: ${AUTH_LANDING}
      API_BASE_URL: ${API_BASE_URL}
      SUPPORT_URL: ${SUPPORT_URL}
    depends_on:
      - redis
    command: [ 'npm', 'start' ]