version: '3.8'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: webrtc-backend-nginx
    ports:
      - ${PROXY_PORT}:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - mongo-express