version: '3.8'
services:
  mongo:
    image: mongo:4.0
    container_name: webrtc-monitor-backend-mongodb
    restart: on-failure
    volumes:
      - mongodata:/data/db
    ports:
      - 27025:27017
  mongo-express:
    image: mongo-express
    container_name: webrtc-monitor-backend-mongo-express
    restart: on-failure
    environment:
      VIRTUAL_HOST: ${MONGO_EXPRESS_DOMAIN}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - 9086:8081
    depends_on:
      - mongo
  nginx:
    image: jwilder/nginx-proxy
    container_name: webrtc-monitor-backend-nginx
    restart: on-failure
    ports:
      - ${PROXY_PORT}:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - mongo-express
  coturn:
    build:
      context: ./coturn-docker
      dockerfile: Dockerfile
    container_name: webrtc-monitor-backend-coturn
    restart: on-failure
    ports:
      - 3478:3478
      - 5349:5349
      - 5766:5766
      - 20000-20020:20000-20020

volumes:
  mongodata: null
